# .streamlit/secrets.toml

# -------- App Lock --------
# Share this password with your internal team only.
APP_PASSWORD="Vidira@4321"

# Optional: restrict allowed usernames (comma-separated).
# If left blank, any username will work as long as password matches.
APP_USERS="reg1,reg2,breakfast1,lunch1,gift1,admin"

# -------- WhatsApp Cloud API --------
WHATSAPP_PHONE_NUMBER_ID="748215838386109"
WHATSAPP_ACCESS_TOKEN="EAAcR2aUPZCIMBQQBH9BZBWZCy3xUtfx8usV4MfNgdNssuIJhXdJiKMBknxMKGqBoHVVdDQKyTu5k583AFsYhHMYqP5VDJWZBZANU2i8HRhkKzDRqcIHuqaYEhbBTQh7jqZAZCNBhRNDOaDJZCZBj87TiAAP0kZAohlZCierH1XBD6tZBRtiNCg7ZAaZAL9LsMx2uomBsdjSwZDZD"
GRAPH_API_VERSION="v20.0"

# -------- Templates --------
# You created these already
TEMPLATE_MAIN="vidira_event_qr_image"
TEMPLATE_EXTRA="vidira_event_food_qr_image"

# WhatsApp template language code (you fixed to English -> 'en')
TEMPLATE_LANG="en"
